In [13]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import sys, os
sys.path.insert(0, os.path.abspath('..'))
from dotenv import load_dotenv
from pathlib import Path
from src.ingestion.loaders import load_file

In [14]:
transactions_file_path = os.getenv("transactions_file_path")
transaction_dataframe = load_file(transactions_file_path)

In [15]:
accounts_file_path = os.getenv("accounts_file_path")
account_dataframe = load_file(accounts_file_path)

In [16]:
transaction_dataframe.drop(columns=["TX_ID", "ALERT_ID", "TX_TYPE"], inplace=True)

In [17]:
transaction_dataframe

,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_AMOUNT,TIMESTAMP,IS_FRAUD
0,6456,9069,465.05,0,False
1,7516,9543,564.64,0,False
2,2445,9356,598.94,0,False
3,2576,4617,466.07,0,False
4,3524,1773,405.63,0,False
...,...,...,...,...,...
1048570,2503,6452,413.57,158,False
1048571,3726,9223,198.53,158,False
1048572,3726,1469,198.53,158,False
1048573,3726,3708,198.53,158,False
1048574,3726,1321,198.53,158,False

In [18]:
account_dataframe.drop(columns=["IS_FRAUD", "ACCOUNT_TYPE", "COUNTRY", "CUSTOMER_ID"], inplace=True)

In [19]:
account_dataframe

      ACCOUNT_ID  INIT_BALANCE  TX_BEHAVIOR_ID
0              0        184.44               1
1              1        175.80               1
2              2        142.06               1
3              3        125.89               1
4              4        151.13               1
...          ...           ...             ...
9995        9995        394.35               5
9996        9996        344.98               5
9997        9997        260.85               5
9998        9998        323.79               5
9999        9999        317.65               5

[10000 rows x 3 columns]

In [24]:
temp_dataframe = transaction_dataframe.merge(account_dataframe, how="inner", left_on="SENDER_ACCOUNT_ID", right_on="ACCOUNT_ID")[["SENDER_ACCOUNT_ID", "RECEIVER_ACCOUNT_ID", "TX_AMOUNT", "TIMESTAMP", "IS_FRAUD", "INIT_BALANCE", "TX_BEHAVIOR_ID"]].rename(columns={"INIT_BALANCE":"SENDER_INIT_BALANCE", "TX_BEHAVIOR_ID":"SENDER_TX_BEHAVIOR_ID"})

In [25]:
temp_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 7 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   SENDER_ACCOUNT_ID      1048575 non-null  int64
 1   RECEIVER_ACCOUNT_ID    1048575 non-null  int64
 2   TX_AMOUNT              1048575 non-null  float64
 3   TIMESTAMP              1048575 non-null  int64
 4   IS_FRAUD               1048575 non-null  bool
 5   SENDER_INIT_BALANCE    1048575 non-null  float64
 6   SENDER_TX_BEHAVIOR_ID  1048575 non-null  int64
dtypes: bool(1), float64(2), int64(4)
memory usage: 49.0 MB

In [26]:
final_dataframe = temp_dataframe.merge(account_dataframe, how="inner", left_on="RECEIVER_ACCOUNT_ID", right_on="ACCOUNT_ID")[["SENDER_ACCOUNT_ID", "RECEIVER_ACCOUNT_ID", "TX_AMOUNT", "TIMESTAMP", "IS_FRAUD", "SENDER_INIT_BALANCE", "SENDER_TX_BEHAVIOR_ID", "INIT_BALANCE", "TX_BEHAVIOR_ID"]].rename(columns={"INIT_BALANCE":"RECEIVER_INIT_BALANCE", "TX_BEHAVIOR_ID":"RECEIVER_TX_BEHAVIOR_ID"})

In [27]:
final_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   SENDER_ACCOUNT_ID        1048575 non-null  int64
 1   RECEIVER_ACCOUNT_ID      1048575 non-null  int64
 2   TX_AMOUNT                1048575 non-null  float64
 3   TIMESTAMP                1048575 non-null  int64
 4   IS_FRAUD                 1048575 non-null  bool
 5   SENDER_INIT_BALANCE      1048575 non-null  float64
 6   SENDER_TX_BEHAVIOR_ID    1048575 non-null  int64
 7   RECEIVER_INIT_BALANCE    1048575 non-null  float64
 8   RECEIVER_TX_BEHAVIOR_ID  1048575 non-null  int64
dtypes: bool(1), float64(3), int64(5)
memory usage: 65.0 MB