In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import sys, os
sys.path.insert(0, os.path.abspath('..'))
from dotenv import load_dotenv
from pathlib import Path
from src.ingestion.loaders import load_file

In [2]:
file_path = os.getenv("accounts_file_path")
account_dataframe = load_file(file_path)

In [3]:
account_dataframe.head(10)

,ACCOUNT_ID,CUSTOMER_ID,INIT_BALANCE,COUNTRY,ACCOUNT_TYPE,IS_FRAUD,TX_BEHAVIOR_ID
0,0,C_0,184.44,US,I,False,1
1,1,C_1,175.80,US,I,False,1
2,2,C_2,142.06,US,I,False,1
3,3,C_3,125.89,US,I,False,1
4,4,C_4,151.13,US,I,False,1
5,5,C_5,140.49,US,I,False,1
6,6,C_6,178.38,US,I,False,1
7,7,C_7,130.33,US,I,False,1
8,8,C_8,147.66,US,I,False,1
9,9,C_9,158.34,US,I,False,1

In [4]:
account_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ACCOUNT_ID      10000 non-null  int64
 1   CUSTOMER_ID     10000 non-null  str
 2   INIT_BALANCE    10000 non-null  float64
 3   COUNTRY         10000 non-null  str
 4   ACCOUNT_TYPE    10000 non-null  str
 5   IS_FRAUD        10000 non-null  bool
 6   TX_BEHAVIOR_ID  10000 non-null  int64
dtypes: bool(1), float64(1), int64(2), str(3)
memory usage: 478.6 KB

In [5]:
account_dataframe["ACCOUNT_TYPE"].value_counts()

ACCOUNT_TYPE
I    10000
Name: count, dtype: int64

In [6]:
account_dataframe["ACCOUNT_TYPE"].value_counts()

ACCOUNT_TYPE
I    10000
Name: count, dtype: int64

In [7]:
account_dataframe["COUNTRY"].value_counts()

COUNTRY
US    10000
Name: count, dtype: int64

In [8]:
account_dataframe["CUSTOMER_ID"].nunique()

10000

In [9]:
account_dataframe.drop(columns=["IS_FRAUD", "ACCOUNT_TYPE", "COUNTRY", "CUSTOMER_ID"])

      ACCOUNT_ID  INIT_BALANCE  TX_BEHAVIOR_ID
0              0        184.44               1
1              1        175.80               1
2              2        142.06               1
3              3        125.89               1
4              4        151.13               1
...          ...           ...             ...
9995        9995        394.35               5
9996        9996        344.98               5
9997        9997        260.85               5
9998        9998        323.79               5
9999        9999        317.65               5

[10000 rows x 3 columns]

In [10]:
account_dataframe[account_dataframe["ACCOUNT_ID"]== 3726]

,ACCOUNT_ID,CUSTOMER_ID,INIT_BALANCE,COUNTRY,ACCOUNT_TYPE,IS_FRAUD,TX_BEHAVIOR_ID
3726,3726,C_3726,198.54,US,I,False,4